### ISSUE TITLE
Empty projects after fresh install

### ISSUE THREAD

**Issue by AndreySlukin** [evernote/zing#364]
I've installed Zing for the first time following this guide https://evernote.github.io/zing/docs/initial-setup, and all projects (both built-in and added by me) seem to be empty:
![screenshot 2018-12-13 at 18 19 31](https://user-images.githubusercontent.com/45238067/49951860-fd0cd580-ff0b-11e8-91f5-265e8636b08d.png)
When running **update_stores** the following errors appeared multiple times:

```
2018-12-13 15:16:48,240 ERROR Failed to run update_stores over /zh_CN/terminology/
Traceback (most recent call last):
  File "/Users/slukin/zing-env/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/__init__.py", line 78, in do_translation_project
    process_stores = self.handle_translation_project(tp, **options)
  File "/Users/slukin/zing-env/lib/python2.7/site-packages/pootle/apps/pootle_app/management/commands/update_stores.py", line 49, in handle_translation_project
    force=options['force'], overwrite=options['overwrite'])
  File "/Users/slukin/zing-env/lib/python2.7/site-packages/pootle/apps/pootle_translationproject/models.py", line 320, in update_from_disk
    store.updater.update_from_disk(overwrite=overwrite)
  File "/Users/slukin/zing-env/lib/python2.7/site-packages/pootle/apps/pootle_store/updater.py", line 354, in update_from_disk
    store_revision=store_revision)
  File "/Users/slukin/zing-env/lib/python2.7/site-packages/pootle/apps/pootle_store/updater.py", line 279, in update
    user, submission_type,
  File "/Users/slukin/zing-env/lib/python2.7/site-packages/pootle/apps/pootle_store/updater.py", line 329, in update_from_diff
    updated, suggested, unsynced_uids = self.update_units(update)
  File "/Users/slukin/zing-env/lib/python2.7/site-packages/pootle/apps/pootle_store/updater.py", line 401, in update_units
    UnitUpdater(unit, update).update_unit()
  File "/Users/slukin/zing-env/lib/python2.7/site-packages/pootle/apps/pootle_store/updater.py", line 220, in update_unit
    self.save_unit()
  File "/Users/slukin/zing-env/lib/python2.7/site-packages/pootle/apps/pootle_store/updater.py", line 191, in save_unit
    self.unit.save(revision=self.update.update_revision)
  File "/Users/slukin/zing-env/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 442, in save
    self.store.update_dirty_cache()
  File "/Users/slukin/zing-env/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 469, in update_dirty_cache
    self.register_all_dirty()
  File "/Users/slukin/zing-env/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 428, in register_all_dirty
    r_con.zincrby(KEY_DIRTY_TREEITEMS, p)
TypeError: zincrby() takes exactly 4 arguments (3 given)
```

What should I try now? Running on MacOS 10.14.1, may this be related?

**Comment by julen** [comment]
Hi @AndreySlukin, it's definitely failing to update stats. Which version of django-rq (and rq) are you using? You can find out so with `pip freeze --local | grep rq`.

**Comment by AndreySlukin** [comment]
Hi @julen, the versions are
django-rq==1.0.0
rq==0.7.1

**Comment by julen** [comment]
Ok, I just see what the problem is:
* We require django-redis 4.6.0, which doesn't pin to any specific versions of redis-py.
* redis-py [accidentally introduced a backwards-incompatible change](https://github.com/andymccurdy/redis-py#zincrby), which causes the traceback you pasted.

I'll try to pin our dependency to [django-redis 4.9.1](https://github.com/niwinz/django-redis/blob/4.10.0/CHANGES.txt#L20), which pins the redis-py version to the latest of the 2.x series.

In the meantime, you can manually force this change by installing `django-redis==4.9.1`, which will downgrade the dependency on redis-py to 2.x. That should get you going, but please let us know how it goes.

**Comment by AndreySlukin** [comment]
After installing django-redis==4.9.1 `update_stores` runs without the mentioned error, but all the stats and files are still empty. The visible difference is a "Stats are out of date" message that keeps repeating after clicking "Refresh now":
![screenshot 2018-12-17 at 15 43 05](https://user-images.githubusercontent.com/45238067/50088298-ac4ef280-0213-11e9-8a7c-fa88f8ac5d85.png)

Tried to remove and re-create zing.db with migrate-initdb-update_stores, same result.

**Comment by julen** [comment]
Are you sure your redis-py dependency was also downgraded to a version < 3.0? `pip freeze --local | grep redis` will help you determine that.

As I see, the last line of the last traceback you shared [points to code from a 3.0 version](https://github.com/andymccurdy/redis-py/blob/3.0.1/redis/_compat.py#L94). Please note how in [2.10.6 that line points nowhere](https://github.com/andymccurdy/redis-py/blob/2.10.6/redis/_compat.py#L94), which makes me think that you still have 3.0.

**Comment by AndreySlukin** [comment]
Yes, have `redis==2.10.6` and the AttributeError doesn't appear anymore after virtual-env restart. refresh_stats and update_stores run without errors. However, the stats are still empty and some languages (Zulu) of tutorial project open as empty, others (French) open normally.
The only error I see is in the JS console when opening such "empty" PO files: undefined is not an object (evaluating 'e.toLocaleString') in app.min.js line 42.

**Comment by julen** [comment]
Cool, thanks for confirming.

It's likely you might have failed/obsolete jobs in the worker queue. You can check in the `/admin/` URL if there are any failed jobs and if so, you can [re-run them via the `retry_failed_jobs` command](https://evernote.github.io/zing/docs/commands#retry-failed-jobs) now that your environment has been fixed. You may also want to check the _rqworker.log_ file in your [`ZING_LOG_DIRECTORY` directory](https://evernote.github.io/zing/docs/settings#zing-log-directory).

Nevertheless and at the same time, I sense that some of the import operations you attempted to run initially have failed, and hence they are not in consistent state, i.e. there should be no _empty_ files whatsoever.

Because you are only setting up the demo _tutorial_ project, I suggest you force-import the contents on disk so that the import can happen from a clean slate: `zing update_stores --project=tutorial --overwrite --force`.

**Comment by AndreySlukin** [comment]
`retry_failed_jobs` did the right thing. And it was also necessary to run `flush_cache --all` to get rid of the "Stats are out of date" message. Big thanks for your support on this issue!
