### ISSUE TITLE
Can't get rid of "Stats are out of date" message

### ISSUE THREAD

**Issue by tariver** [evernote/zing#375]
Hello!
I have a fresh install of Serge+Zing. After converting my project's java properties files to .po files I tried to put them into Zing which I installed following [the guide on Zing's page](https://evernote.github.io/zing/docs/initial-setup).
Initially I had the same problem as in #364, but after following instructions there (installing required version of redis and deleteing-recreating zing.db) overcame them.
But still there is problem, after running `serge push-ts` (which didn't return any errors) I still had about 70 failed jobs. I then run `zing retry_failed_jobs` several times until all of them were gone but one.
![image](https://user-images.githubusercontent.com/36223356/65544750-9695f880-df1c-11e9-8b33-55050b332ccb.png)
And the number of string in my English and German translations have a huge difference, although the individual files' total don't differ.
![image](https://user-images.githubusercontent.com/36223356/65544206-74e84180-df1b-11e9-8052-e6a6baeb0e96.png)

Here is the log of rqworker.log when I run  `zing retry_failed_jobs`
```
2019-09-24T19:35:24 default: pootle.core.mixins.treeitem.update_cache_job(<TranslationProject: /en/mapsurfer/>) (6c182aa5-8834-442e-82b3-82b8c3a55b01)
2019-09-24T19:35:24 update_cached(_calc_last_updated)	0:00:00.005097	/en/mapsurfer/
2019-09-24T19:35:24 KeyError: 'checks'
Traceback (most recent call last):
  File "/opt/zing-env/local/lib/python2.7/site-packages/rq/worker.py", line 700, in perform_job
    rv = job.perform()
  File "/opt/zing-env/local/lib/python2.7/site-packages/rq/job.py", line 500, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 640, in update_cache_job
    instance._update_cache_job(keys, decrement)
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 491, in _update_cache_job
    self.update_cached(key)
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 290, in update_cached
    self.set_cached_value(name, calc_fn())
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 181, in _calc_checks
    result['checks'] = dictsum(result['checks'], item_res['checks'])
KeyError: 'checks'
Traceback (most recent call last):
  File "/opt/zing-env/local/lib/python2.7/site-packages/rq/worker.py", line 700, in perform_job
    rv = job.perform()
  File "/opt/zing-env/local/lib/python2.7/site-packages/rq/job.py", line 500, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 640, in update_cache_job
    instance._update_cache_job(keys, decrement)
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 491, in _update_cache_job
    self.update_cached(key)
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 290, in update_cached
    self.set_cached_value(name, calc_fn())
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 181, in _calc_checks
    result['checks'] = dictsum(result['checks'], item_res['checks'])
KeyError: 'checks'
2019-09-24T19:35:24 Moving job to u'failed' queue
2019-09-24T19:35:24 
2019-09-24T19:35:24 *** Listening on default...
```

Can you please pinpoint me to where the problem is?

**Comment by iafan** [comment]
Before diving deeper into the actual error you're getting, let's try a clean experiment, now that you have technical setup issues resolved.

Here's how you clean your stats and re-calculate them:

1. stop all rqworker instances (`ps ax | grep rqworker` to list the processes, then `kill <pid>` to shutdown each of them)
2. Run `zing flush_cache --rqdata` (this will clean Redis from the old stats)
3. Run rqworker again (see `zing rqworker`)
4. Run `zing refresh_stats` to re-caluclate all the stats.

**Comment by tariver** [comment]
Thank you it worked!
Although after pushing a new language I still get failed job.
What I did - in VCS I created a new file for new language (Kazakh)
```
serge pull config.serge
serge import --lang=kk --disambiguate-keys --no-report
serge localize --lang=kk
serge push-ts --lang=kk --echo-commands --echo-output
```
rqworker had several of these errors:
```
2019-09-25T07:09:44 *** Listening on default...
2019-09-25T07:09:44 default: pootle.core.mixins.treeitem.update_cache_job(<Store: /kk/mapsurfer/auth.po>) (563ae1a1-060c-4372-bf61-928adfd16802)
2019-09-25T07:09:49 OperationalError: database is locked
Traceback (most recent call last):
  File "/opt/zing-env/local/lib/python2.7/site-packages/rq/worker.py", line 700, in perform_job
    rv = job.perform()
  File "/opt/zing-env/local/lib/python2.7/site-packages/rq/job.py", line 500, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 640, in update_cache_job
    instance._update_cache_job(keys, decrement)
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 491, in _update_cache_job
    self.update_cached(key)
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 290, in update_cached
    self.set_cached_value(name, calc_fn())
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 171, in _calc_last_updated
    [self._get_last_updated()] +
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 1516, in _get_last_updated
    max_unit = self.unit_set.all().order_by('-creation_time')[0]
  File "/opt/zing-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 289, in __getitem__
    return list(qs)[0]
  File "/opt/zing-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/opt/zing-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/zing-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/opt/zing-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
OperationalError: database is locked
Traceback (most recent call last):
  File "/opt/zing-env/local/lib/python2.7/site-packages/rq/worker.py", line 700, in perform_job
    rv = job.perform()
  File "/opt/zing-env/local/lib/python2.7/site-packages/rq/job.py", line 500, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 640, in update_cache_job
    instance._update_cache_job(keys, decrement)
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 491, in _update_cache_job
    self.update_cached(key)
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 290, in update_cached
    self.set_cached_value(name, calc_fn())
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/core/mixins/treeitem.py", line 171, in _calc_last_updated
    [self._get_last_updated()] +
  File "/opt/zing-env/local/lib/python2.7/site-packages/pootle/apps/pootle_store/models.py", line 1516, in _get_last_updated
    max_unit = self.unit_set.all().order_by('-creation_time')[0]
  File "/opt/zing-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 289, in __getitem__
    return list(qs)[0]
  File "/opt/zing-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/opt/zing-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/zing-env/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/opt/zing-env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
OperationalError: database is locked
2019-09-25T07:09:49 Moving job to u'failed' queue
2019-09-25T07:09:49 
2019-09-25T07:09:49 *** Listening on default...
```

After command completion there were about 25 failed jobs, but `zing retry_failed_jobs` got rid of them and everything seems to be fine now.

**Comment by iafan** [comment]
> `OperationalError: database is locked`

Are you using SQLite or MySQL?

**Comment by tariver** [comment]
SQLite

**Comment by iafan** [comment]
That’s what I thought. SQLite is good only for quick evaluation purposes, but it is not suitable for production when you have multiple connections that want to write to the database concurrently (main app + workers). You need to switch to MySQL so you won’t get these db locking errors.

**Comment by tariver** [comment]
I see, thank you!
