### ISSUE TITLE
No module named 'syspath_override'

### ISSUE THREAD

**Issue by li-dl** [evernote/zing#480]
Testing on Ubuntu 20.04, `pip install https://github.com/evernote/zing/archive/v0.9.3.zip` succeeds, but when I run `zing --version` it gives:

```
Traceback (most recent call last):
  File "/home/test/test/.venv/bin/zing", line 5, in <module>
    from pootle.runner import main
  File "/home/test/test/.venv/lib/python3.8/site-packages/pootle/runner.py", line 18, in <module>
    import syspath_override  # noqa
ModuleNotFoundError: No module named 'syspath_override'
```

Full log attached: [2020-06-29-Log.txt](https://github.com/evernote/zing/files/4844557/2020-06-29-Log.txt)

The same problem was reproduced on a Debian Buster machine.

See also [Pootle issue 3886](https://github.com/translate/pootle/issues/3886).

**Comment by li-dl** [comment]
The Pootle issue is in the [Pootle FAQ](http://docs.translatehouse.org/projects/pootle/en/stable-2.8.x/faq.html), with the solution:

> You are running Pootle using Python 3, change your virtual environment to Python 2 and try again.

But the [Zing documentation](https://github.com/evernote/zing/blob/v0.9.3/docs/start-introduction.md) says that Zing requires Python 3.

**Comment by jmartens** [comment]
duplicate of #482 which has a proposed fix.
