### ISSUE TITLE
Issue building with python 3.7

### ISSUE THREAD

**Issue by smurfy** [evernote/zing#482]
I having issues building within docker container using pythons 3.7 alpine image.

```
Traceback (most recent call last):
  File "/usr/local/bin/zing", line 5, in <module>
    from pootle.runner import main
  File "/usr/local/lib/python3.7/site-packages/pootle/runner.py", line 18, in <module>
    import syspath_override  # noqa
ModuleNotFoundError: No module named 'syspath_override'
```

This traces back to: https://github.com/evernote/zing/commit/bc1881cb9e945cd8ca86640e813fa0c8a64ee3b3
Older versions of zing work.

**Comment by li-dl** [comment]
Same error message as issue #480.

**Comment by jmartens** [comment]
I was able to fix this by changing `import syspath_override` to  `from .syspath_override import`

**Comment by bdube** [comment]
I make the same change as @jmartens and it seems others do as well. With Python 3.7 listed as the requirement, would this change support 3.7 up to current 3.11, so that a pull request could help solve this?

**Comment by smurfy** [comment]
No idea if its still relevant  or not, but it works with this patch in 3.11 too.
I also needed to tweak the dependencies a bit to proper build.

You can find my tweaks here: https://github.com/smurfy/docker-zing-serge
